### ISSUE TITLE
pledge-agent will need a proximity-assertion artifact

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-async-enroll#1]
In order to prove proximity of the pledge-agent contained in the commissioning tool, the Registrar should provide a signed statement to the pledge-agent attesting to the agent acting on behalf of the Registrar. (This could be a TLS Certificate?)
The pledge should sign this artifact as part of it's voucher-request, such that the Registrar can validate it, and the MASA can pin to the correct Registrar.

**Comment by stfries** [comment]
Section 5.2.4 of BRSKI-AE currently states the call flow for the pledge-agent use case. Here the proximity-certificate is provided optionally in the trigger voucher request. The pledge-agent needs to be provided with that certificate or receives it as part of the TLS handshake with the registrar. If this is changed from optional to mandatory and have it included in the voucher request, the registrar can easily verify, if he is the right recipient. This should nicely align with the core BRSKI approach. 
Proposal to change the top of the call flow to the following: 
  +--------+      +-------+    +-----------+   +--------+   +---------+
   | Pledge |      | Pledge|    | Domain    |   | Domain |   | Vendor  |
   |        |      | Agent |    | Registrar |   | CA     |   | Service |
   |        |      |       |    |  (JRC)    |   |        |   | (MASA)  |
   +--------+      +-------+    +-----------+   +--------+   +---------+
     |                   |              |               |    Internet |
     |       opt: configure             |               |             |
     |       - proximity-registrar-cert |               |             |
     |       - CSR attributes           |               |             |
     |                   |              |               |             |
   [example: trigger voucher and certification request generation ]   |
     |                   |              |               |             |
     |<--trigger VouReq--|              |               |             |
     |(m: proximity-registrar-cert)     |               |             |
     |- Voucher Request->|              |               |             |
     |(o: proximity-registrar-cert)     |               |             |

**Comment by mcr** [comment]
1. pledge agent queries the Domain Registrar for a proximity assertion.
2. the pledge agent forwards the proximity assertion to the pledge
3. the pledge signs the proximity assertion into the voucher-request
4. the MASA validates the proximity assertion in the voucher-request

Is it sufficient if the pledge-agent provides just the certificate of the domain registrar?

**Comment by mcr** [comment]
The trust model between the pledge-agent and the domain registrar needs to be made clear.  It could be completely trusted, or could be completely untrusted.

**Comment by stfries** [comment]
Some thoughts on the trust assumptions between pledge-agent and registrar: 
- Assumption: Pledge-agent provides registrar certificate to pledge
- Pledge includes it in the voucher request 
- Registrar verifies that it is the intended Registrar
- Registrar and MASA must have an established trust relation (based on exchanged rootCAs certs
- After onboarding Registrar must verify the audit log to ensure that all pledges in his domain have been onboarded. 
- If the verification of the audit log fails for a specific pledge, is an indication for a missing pledge or a misbinding to a faked registrar.	(Misbinding of pledge to a faked registrar addressed in BRSKI  section 11.4.)

**Comment by stfries** [comment]
Further discussed in issue #4  and issue #5

**Comment by stfries** [comment]
Closed as further addressed in #4 and #5
