### ISSUE TITLE
Agent-signed-data as part of 

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-async-enroll#12]
Should the agent-signed data in the trigger message from the registrar-agent to the pledge relate to a new module "ietf-voucher-request-trigger" or be part of the existing module "ietf-voucher-request" ?

{
    "alg": "ES256", 
    "kid": "base64encodedvalue=="      
}
{
  "ietf-voucher-request-trigger:agent-signed-data": {  // alternatively part of ietf-voucher-request:agent-signed-data
    "created-on": "2021-04-16T00:00:01.000Z",         
    "serial-number": "callee4711"                    
  }
}
{
    SIGNATURE
}

Reasoning can be provided for both. As the agent-signed-data is also part of the pledge-voucher-request, it may be better to include it into the existing module.

**Comment by mcr** [comment]
1. agent already has the pledge to return the *Pledge's* serial-number (from the IDevID), via scan of the pledge and/or connect. 
2. agent sends this JOSE signed document to Pledge.
3. Pledge includes this, as part of its voucher-request.

**Comment by mcr** [comment]
In the voucher-request, agent-signed-data is the JOSE object.

**Comment by stfries** [comment]
Voucher Example

   {
      "alg": "ES256",
      "x5c": ["MIIB2jCC...dA=="]
   }
   {
     "ietf-voucher-request:voucher": {
      "created-on": "2021-04-16T00:00:02.000Z",
      "nonce": "eDs++/FuDHGUnRxN3E14CQ==",
      "serial-number": "callee4711",
      "assertion": "agent-proximity",
      "agent-provided-proximity-registrar-cert": "base64encodedvalue==",
      "agent-signed-data": "base64encodedvalue==",
      "agent-sign-cert": "base64encodedvalue=="
     }
   }
   {
       SIGNATURE
   }

**Comment by mcr** [comment]
@mcr to send YANG proposal and diagrams.

**Comment by stfries** [comment]
Based on the discussion and the proposal from Michael I conclude that there should be three new leafs in the voucher-request:
- agent-signed-data
- agent-provided-proximity-registrar-cert
- agent-sign-cert (optional)

These were included in the [YANG description](https://github.com/anima-wg/anima-brski-async-enroll/blob/main/ietf-async-voucher-request.yang) based on the voucher-request definition in RFC 8995
