### ISSUE TITLE
What does the YANG look like for the extension to the voucher(-request)?

### ISSUE THREAD

**Issue by elear** [anima-wg/anima-brski-async-enroll#14]
Do we augment 8995?  Do we augment 8366?  Do we need to do both? What does it mean to augment something that augments something?

**Comment by mcr** [comment]
Hi, I'm working on that pull request right now.  #15.  
I don't know how to manage YANG stuff in a bare MT / XML Makefile.  
We extend 8995 for the voucher-request.
There are some practical YANG practices that I'm missing.

**Comment by stfries** [comment]
I enhanced the voucher-request with two additional leafs for the agent-sign-cert and the agent-provided-proximity-certificate.

**Comment by stfries** [comment]
YANG module for the extension of the voucher request will be put into the next update of the draft. The will need more investigation by the YANG doctor.

**Comment by mcr** [comment]
closed by #15
