### ISSUE TITLE
Terminology change for PULL/PUSH model

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-async-enroll#3]
The currently used terminology PULL and PUSH may lead to misunderstanding to which component the model actually applies. The term should clarify, that the pledge is either acting as a client or as a server. 
Based on this it is proposed to rename: 
-    PULL mode to pledge-client mode (pledge initiates the bootstrapping)
-    PUSH mode to pledge-server mode (pledge is waiting for being triggered for bootstrapping

**Comment by toerless** [comment]
Btw: if the role is used to describe the transport level connection role,
then i think initiator/responder are preferrably to client/server.

Cheers
    Toerless

On Fri, Mar 12, 2021 at 03:21:04AM -0800, stfries wrote:
> The currently used terminology PULL and PUSH may lead to misunderstanding to which component the model actually applies. The term should clarify, that the pledge is either acting as a client or as a server. 
> Based on this it is proposed to rename: 
> -    PULL mode to pledge-client mode (pledge initiates the bootstrapping)
> -    PUSH mode to pledge-server mode (pledge is waiting for being triggered for bootstrapping
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/anima-wg/anima-brski-async-enroll/issues/3

-- 
---
***@***.***

**Comment by stfries** [comment]
This would be fines as well resulting in 
-     PULL mode = pledge-initiator mode (pledge initiates the bootstrapping)
-     PUSH mode to pledge-responder mode (pledge is waiting for being triggered for bootstrapping

**Comment by EskoDijk** [comment]
pledge-initiator mode / pledge-responder mode sounds good!

**Comment by stfries** [comment]
Based on the (verbal) discussion we had, the change will be incorporated into the the next version of the draft. 
Issue can be closed in next Design Team meeting (April 1).

**Comment by EskoDijk** [comment]
@stfries this issue can be closed as soon as the updated text is in Github!

**Comment by stfries** [comment]
Addressed in new version from May 27, 2021
