### ISSUE TITLE
Trust relation between registrar-agent and registrar

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-async-enroll#4]
It is proposed to assume an already available LDevID on the registrar-agent (former pledge-agent), as it is considered to be a site/domain component. This LDevID can be provided by a prior BRSKI run or by other means. 
The registrar-agent uses this LDevID for (D)TLS client authentication at the protected registrar endpoints.

**Comment by mcr** [comment]
Does this registrar-agent certificate need any special extensions?

**Comment by stfries** [comment]
No, it should be identifiable by the registrar by its name. No specific extension intended so far.

**Comment by stfries** [comment]
Closed as further addressed in #9
#9 proposes a solution to allow the registrar and/or the MASA to verify and log the bootstrapping registrar-agent
