### ISSUE TITLE
after the LDevID has been provisioned, what next?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-async-enroll#6]
Do we need to provide for some application specific connection data to be returned through the registrar-agent to the pledge, to further configure it to the right network, and/or even to the right set of peer pledges?

**Comment by stfries** [comment]
Not sure if this is part of the bootstrapping. BRSKI-AE, as BRSKI targets the trust establishment between the pledge an a domain. Preceding steps building on that trust relation may be described in separate documents.

**Comment by mcr** [comment]
The registrar agent (formerly known as pledge-agent) would be part of some use-case specific commissioning device, and so that commissioning tool would know how to do any use case-specific configuration.

We have bootstrap with generic LDevID, there could be a second bootstrap leveraging that LDevID to get, e.g., OPC UA, BACnet, etc. 
This would use a functionality like EST, also can be done with PULL approach.

We may want additional consideration with provisioning CWT or JWT into the pledge, and so that additional onfiguration via HTTPS. (But that would be out of scope)
