### ISSUE TITLE
the registrar-agent LDevID should be short-lived

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-async-enroll#7]
The LDevID issued by the registrar to the registrar-agent should be short-lived (on the order of a day to a week).  Thus there is no need for long-term protection of the device.

New LDevID can be issued every morning if needed.

Also, for maintenance actions later on, that there is no requirement to use the same tool.
We want the technicians to be able to use whatever device they have available.

_Security Considerations on lifetime of the Agent LDevID._

**Comment by mcr** [comment]
Maintenance work could be authorized by some token that is provided with the ticket asking for the work to be done.

**Comment by stfries** [comment]
Providing the recommendation to make this a short-lived LDevID for the Registrar Agent seems fine for me. This can be added to the corresponding section and also to the Security Consideration section.

Regarding the token for maintenance access, this may be out of scope for BRSKI-AE as it would utilize the existing trust established through BRSKI/BRSKI-AE to validate such a token.

**Comment by stfries** [comment]
will be taken into the security consideration section and also in the corresponding section of use case 2. Will be closed with upload of a new version

**Comment by stfries** [comment]
Addressed in new version from May 27, 2021
