### ISSUE TITLE
do we need a way to provoke premature renewal in order to transfer ownership?

### ISSUE THREAD

**Issue by mcr** [anima-wg/anima-brski-async-enroll#8]

**Comment by stfries** [comment]
If the pledge is triggered for a voucher-request and an enrollment-request it should be underlined, that it maintains its currently issued LDevID certificate. The acceptance of a new LDevID certificate by the pledge depends later on the availability of a voucher and a new LDevID provided by the registrar. This means that the registrar and the MASA still need to verify the voucher-request. 

Maybe it should be noted that the device needs to be rest before an owner transfer can happen. I would expect this in any case to avoid that the new owner has any possibility to leverage credentials issued by the prior owner.

Proposal to note this in the corresponding section and also in the security considerations.

**Comment by EskoDijk** [comment]
Question from the call: are there any use cases in which the Registrar-agent comes by to do EST re-enrollment for a device?
(This may be a different Registrar-agent as last time; as long as it's an authentic Registrar-agent of the current Domain/CA the device is in.

This question may be more relevant when LDevIDs are short-lived and/or installing a network infrastructure in the building takes very long for some reason.

**Comment by mcr** [comment]
If the device has a valid CA, then it should not be possible to trigger a new voucher-request without doing some kind of physical action to the device (factory reset button,, etc.)

**Comment by mcr** [comment]
It should be possible to trigger a *EST* level (re-)enroll  again, as long as it does not cause a change of CA.

**Comment by mcr** [comment]
This is probably part of a new document, not part of bootstrapping.
