### ISSUE TITLE
Bootstrapping registrar-agent association

### ISSUE THREAD

**Issue by stfries** [anima-wg/anima-brski-async-enroll#9]
Proposal to include a signed statement (e.g., the pledge serial number) from the registrar-agent into the voucher request trigger to the pledge. This is in addition to the registrar certificate, which is also provided by the registrar-agent for  inclusion into the pledge's voucher request. This requires another leaf in the voucher request (e.g.  agent-signed-pledge-SN).

This allows the registrar in addition to the registrar-agent TLS authentication with the LDevID(RegAgt) to log the bootstrapping registrar-agent for a specific pledge. If the LDevID(RegAgt) is short lived (e.g., 24h) or a different registrar-agent is used for providing the pledge voucher-request to the registrar, a more detailed logging can be provided with information about the initial registrar-agent.

The call flow after discovery may perform as:
```
     +-------+                          +----------+   
     | Pledge|                          | Registrar|   
     |       |                          | Agent    |   
     |       |                          |          |   
     +-------+                          +----------+   
       |                                   |       
       |                                   | - sign pledge SN 
       |                                   |   with LDevID/Reg     
       |<- trigger pledge voucher-request -|       
       | (registrar-cert, signed pledge SN)|       
       |                                   |       
       |-------- Voucher-Request --------->| - store       
       | (w/nonce, reg-cert, signedSN )    |   voucher-request    
       |                                   |       
       |<--- trigger enrollment request ---|       
       |                                   |       
       |------- Enrollment-Request ------->| - store       
       |                                   |   enrollment request    
```

The registrar can log the signed pledge SN to be able to verify, which registrar-agent was used for bootstrapping, also in the case that the agent was changed during the process or the original agent certificate expired during the process. The signed SN could be another new leaf in the voucher, in addition to the agent-provided-registrar-certificate. The MASA would neglect this information.

**Comment by mcr** [comment]
I think that this might be key.
What you are really providing is a new artifact, the registrar-agent-proximity statement, which assures the registrar and the MASA that the registrar agent really is close to the pledge.  
We might want to change the order here, and we might want to have the Registrar Agent sign the pledge's nonce.
That could occur after the voucher-request is made.
However, I think you are thinking about it the other way, that the registrar-agent-proximity statement would be included in the voucher-request.
@pritikin might have some views.

**Comment by pritikin** [comment]
I agree that this seems like something similar to the "proximity-registrar-cert" normally populated by the pledge in the pledge voucher request and [verified by the registrar](https://www.ietf.org/archive/id/draft-ietf-anima-bootstrapping-keyinfra-45.html#name-pledge-requests-voucher-fro).

Because of the PSK authentication method described in BRSKI-AE ( -01, section 5.2.3.1 ) we can't really mirror the way the proximity-registrar-cert leaf is populated from the TLS handshake so the best that can be done is whatever the PSK method is using. The registrar-agent "knows" the pledge serial number from the mDNS discovery from section 5.2.2.2? As confirmed by the successful PSK generation and use? Regardless of if this is placed in the voucher-request by the pledge or the registrar-agent it doesn't provide any connection to the registrar agent's identity though. Meaning it doesn't really meet the same goal as the proximity-registrar-cert.

**Comment by mcr** [comment]
@pritikin I think that the PSK authenticated TLS between the registrar-agent and pledge is going away.  It will be HTTP (maybe CoAP. Maybe CORECONF. Maybe over BTLE rather than IP), and there will be object security rather than session security for that part.

**Comment by pritikin** [comment]
I see the reasoning ... but if all '[PSK usage in TLS establishment](https://tools.ietf.org/html/draft-ietf-anima-brski-async-enroll-01#section-9.2)' and etc goes away then there is no artifact from the communications between the pledge and the registrar-agent that demonstrates "proximity" even to the admittedly weak level of "well, we were able to do a TLS handshake on the local network". 

At that point the registrar-agent signing _something_ -- either sending a signed message to the pledge as in the initial msg or after receiving the voucher-request as MCR suggested -- are the only two options. Either meets the limited goal of "log the bootstrapping registrar-agent for a specific pledge" but doing in the first message means it also logs that this is the message the pledge is responding to. That sorta shows "proximity in that it shows the registrar-agent that initiated the exchange?

**Comment by stfries** [comment]
Yes regarding the TLS question. TLS between the pledge and the registrar-agent was discussed to be removed in favor of object security. This leaves it open, which transport is going to be used. 

Also yes, regarding the second point. The signed statement from the registrar-agent was intended to let the registrar log, which registrar-agent was in contact with the pledge in the first place which may be the same but with a different short-lived certificate or a different one. As there is no trust established at the time of triggering the voucher request creation the pledge is not able to verify something signed by the registrar-agent at this point in time. The intention was rather to include this statement into the voucher-request to let the infrastructure do the verification. It is weaker than the proximity assertion in BRSKI, which should be reflected in the assertion type in the MASA issued voucher.

Signing a nonce provide in an additional handshake with the pledge, which then appears in both, the signed object from the registrar-agent and the voucher-request from the pledge may be an option, but the connection between the pledge and the registrar-agent is not secured and requires an additional handshake and a further endpoint. 

Signing the pledge voucher-request by the registrar-agent before providing it to the registrar may not add to the security of the TLS connection between the registrar-agent and the registrar, which is also mutually authenticated. This leaves out the case in which the voucher-request was collected by a (legitimate) registrar-agent with a different LDevID.

As said above, the assertion at the end is likely weaker than "registrar-proximity", therefore the intention was to let the MASA provide a "verified" or "logged" assertion or a new assertion, which would need to be defined.

**Comment by stfries** [comment]
BTW, I already did some of the edits discussed during IETF 110, like removing TLS between pledge and registrar-agent, but did this in a local copy of the draft.  I will upload an intermediate version if it is more mature. I intended to first discuss the issue in the design team before.

**Comment by mcr** [comment]
Having the registrar-agent and the pledge exchange some kind of signed nonce is a good thing.  In order to know which direction is better, we need to think about who is evaluating the signed thing.
If it is the registrar, then a signature from the registrar-agent has value.  Since there is already a trust relationship between the registrar and registrar-agent, and since the voucher-request is coming via the registrar-agent, I think that there is not really a lot of value in trying to defend the registrar from a rogue registrar-agent.
A signature from the pledge on something that the registrar-agent provided can be validated by the MASA.
This suggests to me that having the registrar-agent's public key be pinned by the voucher-request is the right thing.

**Comment by stfries** [comment]
Lets discuss the "something" tomorrow. The intention of including the signed serial number was to let the registrar validate if it was an authorized registrar-agent, specifically in the case of a credential change at the agent side. Just using the certificate of the registrar agent may not be sufficient. That said, I had in mind the registrar would evaluate the "something". I'm not even sure the MASA needs to be involved in that. If it needs to validate the "something", the signed serial number may not work if the certificate of the registrar agent is not available at the MASA.

**Comment by pritikin** [comment]
Just to recap the questions i'm seeing here. I was forming a reply but stfries' call to discuss in a meeting makes sense:
* is this a worthwhile idea (seems like we all agree it is) 
* what information is-to-be-signed
* where in the message sequence this originates
* which entity or entities check the signed value and what "authorization" decisions or log entries result
* is anything pinned into the ultimate voucher

**Comment by stfries** [comment]
As an answer to the questions above:

-     is this a worthwhile idea (seems like we all agree it is): 
* yes, was agreed in design Team meeting on April 8th
-     what information is-to-be-signed: 
* currently we assume the device serial number of the pledge, which is also contained in the IDevID cert.
-     where in the message sequence this originates: 
* the device serial number is known upfront to the registrar-agent and the signed object from the registrar-agent containing this serial number would be part of the trigger message to the pledge and also included in the pledge signed voucher-request
-     which entity or entities check the signed value and what "authorization" decisions or log entries result:
* the registrar will check the signed value and log the information to keep track of which registrar was actually in contact with the 
pledge. The registrar may use the information in addition to the info about the submitting registrar-agent, which can be identified based on the TLS handshake with the registrar. The MASA may verify the signed object, if it possesses the domain CA certificate. On the other hand, the MASA may not (or must not) be aware of a registrar-agent so he may neglect the information. The intention is to let the registrar identify the agent used for bootstrapping (for the audit trail). If the MASA can verify the signature on the signed object the assertion may be "agent proximity " but it may be sufficient to use the existing assertion "logged" or "verified", which are weaker than "proximity".
-     is anything pinned into the ultimate voucher
* currently we assume the domain certificate in the voucher as in BRSKI

**Comment by stfries** [comment]
Proposal from design team meeting:
Include LDevID certificate from registrar-agent into registrar generated voucher-request containing the prior signed voucher. This enables the MASA to verify also the registrar-agent certificate assumed that the registrar certificate and the registrar-agent certificate can be traced to the same rootCA.

**Comment by stfries** [comment]
Note to the proposal above: It should be clear that the registrar in this case must be able to fetch the corresponding certificate for the registrar-agent to verify the signedSN. 
This is easy for the case that the registrar-agent uses the same LDevID for the signature and for authentication in the TLS establishment to the registrar. In case of short-lived certificates, the LDevID for the signature may already be different as for the TLS client authentication. This may increase the effort on the registrar to be able to fetch the corresponding certificate to verify the signedSN. Including it in the signed object from the pledge would safe this effort but would lead to the double transfer of the registrar-agent certificate.

**Comment by stfries** [comment]
Addressed in new version from May 27, 2021
